### ISSUE TITLE
Locking up on v10

### ISSUE THREAD

**Issue by dsshap** [actionhero/ah-newrelic-plugin#1]
hangs here:
12:04:00 web.1 | 2015-02-12 12:04:00 - debug: loading initializer: /Users/dave/../app/node_modules/ah-newrelic-plugin/initializers/newrelic.js
12:04:00 web.1 | 2015-02-12 12:04:00 - info: actionhero member 10.1.10.18 has joined the cluster

**Comment by evantahler** [comment]
Embarrassing.  https://github.com/evantahler/ah-newrelic-plugin/commit/336ee92fed65c2faad46522ee78eae268d5512a4

Try now!
