### ISSUE TITLE
Compatibility with ActionHero 18

### ISSUE THREAD

**Issue by ghost** [actionhero/ah-newrelic-plugin#9]
I see (one of) the latest commit is about updating the codebase for it to work with AH 18.
I'm not sure if I followed correctly but initializers now have a class structure, don't they? Not sure if the plugin works with AH 18 as it.

**Comment by ghost** [comment]
Looking into it and coming up with a PR.

**Comment by evantahler** [comment]
solved by https://github.com/actionhero/ah-newrelic-plugin/pull/10
